spring:
  zipkin:
    baseUrl: http://zipkinserver:9411  
    enabled:true    


logging:
   level:
     root: INFO
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  healthcheck:
      enabled: true
  lease:
      duration: 5
      
      
---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://zipkinserver:9411            

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/    