spring:
  zipkin:
    baseUrl:http://zipkinserver:9411  
    enabled:true    


logging:
   level:
     root: INFO
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  healthcheck:
      enabled: true
  lease:
      duration: 5